version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: nestjs-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app/api
      - /usr/src/app/api/node_modules
  frontend:
    build:
      context: ./frontend
    container_name: svelte-ui
    restart: always
    stdin_open: true
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/usr/src/app/my-app
      - /usr/src/app/my-app/node_modules