version: "3"
services:
  web:
    container_name: docker-app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: dbmongo
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none
